/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLayoutRouteRouteImport } from './routes/admin/_layout/route'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutMenuRouteImport } from './routes/admin/_layout/menu'
import { Route as AdminLayoutLoginRouteImport } from './routes/admin/_layout/login'
import { Route as AdminLayoutHomepageRouteImport } from './routes/admin/_layout/homepage'
import { Route as AdminLayoutDeliveryRouteImport } from './routes/admin/_layout/delivery'
import { Route as AdminLayoutCategoriesRouteImport } from './routes/admin/_layout/categories'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRouteRoute = AdminLayoutRouteRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutMenuRoute = AdminLayoutMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutLoginRoute = AdminLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutHomepageRoute = AdminLayoutHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutDeliveryRoute = AdminLayoutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutCategoriesRoute = AdminLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminLayoutRouteRouteWithChildren
  '/admin/categories': typeof AdminLayoutCategoriesRoute
  '/admin/delivery': typeof AdminLayoutDeliveryRoute
  '/admin/homepage': typeof AdminLayoutHomepageRoute
  '/admin/login': typeof AdminLayoutLoginRoute
  '/admin/menu': typeof AdminLayoutMenuRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminLayoutCategoriesRoute
  '/admin/delivery': typeof AdminLayoutDeliveryRoute
  '/admin/homepage': typeof AdminLayoutHomepageRoute
  '/admin/login': typeof AdminLayoutLoginRoute
  '/admin/menu': typeof AdminLayoutMenuRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/_layout': typeof AdminLayoutRouteRouteWithChildren
  '/admin/_layout/categories': typeof AdminLayoutCategoriesRoute
  '/admin/_layout/delivery': typeof AdminLayoutDeliveryRoute
  '/admin/_layout/homepage': typeof AdminLayoutHomepageRoute
  '/admin/_layout/login': typeof AdminLayoutLoginRoute
  '/admin/_layout/menu': typeof AdminLayoutMenuRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/settings'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/delivery'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/settings'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/_layout'
    | '/admin/_layout/categories'
    | '/admin/_layout/delivery'
    | '/admin/_layout/homepage'
    | '/admin/_layout/login'
    | '/admin/_layout/menu'
    | '/admin/_layout/settings'
    | '/api/auth/$'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLayoutRouteRoute: typeof AdminLayoutRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/menu': {
      id: '/admin/_layout/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminLayoutMenuRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/login': {
      id: '/admin/_layout/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLayoutLoginRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/homepage': {
      id: '/admin/_layout/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminLayoutHomepageRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/delivery': {
      id: '/admin/_layout/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminLayoutDeliveryRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/categories': {
      id: '/admin/_layout/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminLayoutCategoriesRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
  }
}

interface AdminLayoutRouteRouteChildren {
  AdminLayoutCategoriesRoute: typeof AdminLayoutCategoriesRoute
  AdminLayoutDeliveryRoute: typeof AdminLayoutDeliveryRoute
  AdminLayoutHomepageRoute: typeof AdminLayoutHomepageRoute
  AdminLayoutLoginRoute: typeof AdminLayoutLoginRoute
  AdminLayoutMenuRoute: typeof AdminLayoutMenuRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteRouteChildren: AdminLayoutRouteRouteChildren = {
  AdminLayoutCategoriesRoute: AdminLayoutCategoriesRoute,
  AdminLayoutDeliveryRoute: AdminLayoutDeliveryRoute,
  AdminLayoutHomepageRoute: AdminLayoutHomepageRoute,
  AdminLayoutLoginRoute: AdminLayoutLoginRoute,
  AdminLayoutMenuRoute: AdminLayoutMenuRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteRouteWithChildren =
  AdminLayoutRouteRoute._addFileChildren(AdminLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLayoutRouteRoute: AdminLayoutRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
